# Generated by Django 5.0.3 on 2024-04-08 15:50

import common.models
import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Отзыв места',
                'verbose_name_plural': 'Отзывы мест',
                'db_table': 'feedback_place',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedBackPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, verbose_name='Название')),
                ('_file_format', models.CharField(blank=True, db_index=True, default=None, editable=False, max_length=70, null=True, verbose_name='Формат изображения')),
                ('_file_width', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Ширина изображения')),
                ('_file_height', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Высота изображения')),
                ('file', models.ImageField(max_length=5000, storage=common.storage.OverwriteStorage(), upload_to='app/feedback_place/', verbose_name='Изображение отзыва')),
            ],
            options={
                'verbose_name': 'Изображение отзыва места',
                'verbose_name_plural': 'Изображения отзывов мест',
                'db_table': 'feedback_place_image',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес места')),
                ('work_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время работы')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'db_table': 'place',
                'abstract': False,
            },
            bases=(models.Model, common.models.MultiplyImagesMixin),
        ),
        migrations.CreateModel(
            name='PlaceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
            ],
            options={
                'verbose_name': 'Контакт места',
                'verbose_name_plural': 'Контакты мест',
                'db_table': 'place_contact',
            },
            bases=(common.models.CallCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlaceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, verbose_name='Название')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('_file_format', models.CharField(blank=True, db_index=True, default=None, editable=False, max_length=70, null=True, verbose_name='Формат изображения')),
                ('_file_width', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Ширина изображения')),
                ('_file_height', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Высота изображения')),
                ('file', models.ImageField(max_length=5000, storage=common.storage.OverwriteStorage(), upload_to='app/place/', verbose_name='Изображение места')),
            ],
            options={
                'verbose_name': 'Изображение места',
                'verbose_name_plural': 'Изображения мест',
                'db_table': 'place_image',
                'abstract': False,
            },
            bases=(models.Model, common.models.MultiplyImagesMixin),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег места',
                'verbose_name_plural': 'Теги мест',
                'db_table': 'tag_place',
            },
        ),
        migrations.CreateModel(
            name='TagPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главный тег')),
            ],
            options={
                'verbose_name': 'Тег места',
                'verbose_name_plural': 'Теги мест',
                'db_table': 'tags_places',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание пути к месту',
                'verbose_name_plural': 'Описания пути к местам',
                'db_table': 'way_place',
            },
        ),
        migrations.CreateModel(
            name='WayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, verbose_name='Название')),
                ('_file_format', models.CharField(blank=True, db_index=True, default=None, editable=False, max_length=70, null=True, verbose_name='Формат изображения')),
                ('_file_width', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Ширина изображения')),
                ('_file_height', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Высота изображения')),
                ('file', models.ImageField(max_length=5000, storage=common.storage.OverwriteStorage(), upload_to='app/way/', verbose_name='Изображение пути')),
            ],
            options={
                'verbose_name': 'Изображение пути к месту',
                'verbose_name_plural': 'Изображения пути к местам',
                'db_table': 'way_place_image',
                'abstract': False,
            },
        ),
    ]
