# Generated by Django 5.0.3 on 2024-04-06 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackplace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks_places', to=settings.AUTH_USER_MODEL, verbose_name='Публицист'),
        ),
        migrations.AddField(
            model_name='feedbackplaceimage',
            name='feedback_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.feedbackplace', verbose_name='Отзыв места'),
        ),
        migrations.AddField(
            model_name='feedbackplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_feedbacks', to='place.place', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='placecontact',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='place.place', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='placeimages',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.place', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='tagplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_tags', to='place.place', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='tagplace',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_places', to='place.tag', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(db_index=True, related_name='places', through='place.TagPlace', to='place.tag', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='way',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='wayimage',
            name='way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.way', verbose_name='Путь к месту'),
        ),
    ]
