# Generated by Django 5.0.3 on 2024-04-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ways_place', to='place.place', verbose_name='Место'),
        ),
    ]
