# Generated by Django 5.0.3 on 2024-04-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_ways', to='place.place', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='feedbackplace',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        )
    ]
