# Generated by Django 5.0.3 on 2024-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackplaceimage',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='wayimage',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Название'),
        ),
    ]
