# Generated by Django 5.0.3 on 2024-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_feedbackplaceimage_name_alter_placeimages_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecontact',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт'),
        ),
    ]
