# Generated by Django 5.0.3 on 2024-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_initial'),
        ('user', '0002_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites_place',
            field=models.ManyToManyField(blank=True, related_name='user_subscribers', to='place.place', verbose_name='Избранные посты'),
        ),
    ]
