# Generated by Django 5.0.3 on 2024-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='user', max_length=50, null=True, verbose_name='username'),
        ),
    ]
