# Generated by Django 5.0.3 on 2024-04-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Отзыв маршрута',
                'verbose_name_plural': 'Отзывы маршрутов',
                'db_table': 'feedback_route',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedBackRouteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, verbose_name='Название')),
                ('file', models.ImageField(blank=True, max_length=5000, upload_to='', verbose_name='Изображение')),
                ('_file_format', models.CharField(blank=True, db_index=True, default=None, editable=False, max_length=70, null=True, verbose_name='Формат изображения')),
                ('_file_width', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Ширина изображения')),
                ('_file_height', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Высота изображения')),
            ],
            options={
                'verbose_name': 'Изображение отзыва маршрута',
                'verbose_name_plural': 'Изображения отзывов маршрутов',
                'db_table': 'feedback_route_image',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('travel_time', models.TimeField(verbose_name='Время прохождения')),
                ('distance', models.FloatField(verbose_name='Дистанция')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'route',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Очередность места')),
            ],
            options={
                'verbose_name': 'Связь маршрута-места',
                'verbose_name_plural': 'Связь маршрутов-мест',
                'db_table': 'route_place',
            },
        ),
    ]
