# Generated by Django 5.0.3 on 2024-04-13 11:36
import django
from django.db import migrations, models

import common


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='RouteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, verbose_name='Название')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('_file_format',
                 models.CharField(blank=True, db_index=True, default=None, editable=False, max_length=70, null=True,
                                  verbose_name='Формат изображения')),
                ('_file_width',
                 models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True,
                                             verbose_name='Ширина изображения')),
                ('_file_height',
                 models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True,
                                             verbose_name='Высота изображения')),
                ('file',
                 models.ImageField(max_length=5000, storage=common.storage.OverwriteStorage(), upload_to='app/route/',
                                   verbose_name='Изображение места')),
                ('route',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='route.route',
                                   verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Изображение пути',
                'verbose_name_plural': 'Изображения путей',
                'db_table': 'route_image',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feedbackroute',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
