# Generated by Django 5.0.3 on 2024-04-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
    ]
