# Generated by Django 5.0.3 on 2024-04-13 15:54

import common.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_route_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, verbose_name='Название')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('_file_format', models.CharField(blank=True, db_index=True, default=None, editable=False, max_length=70, null=True, verbose_name='Формат изображения')),
                ('_file_width', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Ширина изображения')),
                ('_file_height', models.PositiveIntegerField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name='Высота изображения')),
                ('file', models.ImageField(max_length=5000, storage=common.storage.OverwriteStorage(), upload_to='app/route/', verbose_name='Изображение места')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='route.route', verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Изображение пути',
                'verbose_name_plural': 'Изображения путей',
                'db_table': 'route_image',
                'abstract': False,
            },
        ),
    ]
