# Generated by Django 5.0.3 on 2024-04-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_routeimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackroute',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
