# Generated by Django 5.0.3 on 2024-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_alter_feedbackroute_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrouteimage',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='routeimages',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Название'),
        ),
    ]
