name: build, push and deploy
on:  
  push:
    branches: 
      - "f/self-hosted-runner"

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3
      - name: login to nexus
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_HOST }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD}}
      - name: build and push
        run: |
          ${{ steps.vars.outputs.sha_short }}
          docker build -t ${{ secrets.NEXUS_HOST }}/dagestanback:latest -t ${{ secrets.NEXUS_HOST }}/dagestanback:${{ github.run_number }} .
      - name: push docker image
        run: |
          docker push ${{ secrets.NEXUS_HOST }}/dagestanback:latest
          docker push ${{ secrets.NEXUS_HOST }}/dagestanback:${{ github.run_number }}

  deploy:
    needs: build_and_push
    runs-on: self-hosted
    steps:
      - name: login to nexus
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_HOST }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD}}
      - name: Docker stop, pull and up
        run: |
          ssh ${{ secrets.TEST_HOST }} -- docker login ${{ secrets.NEXUS_HOST }} --username ${{ secrets.NEXUS_USERNAME }} --password ${{ secrets.NEXUS_PASSWORD}} && docker-compose pull && docker-compose stop && docker-compose up -d

  cleanup:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Throw away all the garbage
        run: |
          ssh ${{ secrets.TEST_HOST }} -- docker system prune -f --filter "label!=keep"
