name: build, push and deploy
on:  
  push:
    branches: 
      - "develop"

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3
      - name: login to nexus
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_HOST }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD}}
      - name: Extract version from git tag
        id: vars
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: build and push
        run: |
          docker build -t ${{ secrets.NEXUS_HOST }}/dagestanback:latest .
          docker build -t ${{ secrets.NEXUS_HOST }}/dagestanback:{{ env.VERSION }} .
      - name: push docker image
        run: |
          docker push ${{ secrets.NEXUS_HOST }}/dagestanback:latest
          docker push ${{ secrets.NEXUS_HOST }}/dagestanback:{{ env.VERSION }}

  deploy:
    needs: build_and_push
    runs-on: self-hosted
    steps:
      - name: Docker stop, pull and up
        run: |
          ssh ${{ secrets.TEST_HOST }} -- docker-compose pull
          ssh ${{ secrets.TEST_HOST }} -- docker-compose stop 
          ssh ${{ secrets.TEST_HOST }} -- docker-compose up -d

  cleanup:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Throw away all the garbage
        run: |
          ssh ${{ secrets.TEST_HOST }} -- docker system prune -f --filter "label!=keep"
