name: build, push and deploy
on:  
  push:
    branches: 
      - "develop"

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3
      - name: login to nexus
        run: |
          echo '${{ secrets.NEXUS_PASSWORD }}' | docker login -u ${{ secrets.NEXUS_USERNAME }} --password-stdin  ${{ secrets.NEXUS_HOST }} 
      - name: build and push
        run: |
          ${{ steps.vars.outputs.sha_short }}
          docker build -t ${{ secrets.NEXUS_HOST }}/dagestanback:latest -t ${{ secrets.NEXUS_HOST }}/dagestanback:${{ github.run_number }} .
      - name: push docker image
        run: |
          docker push ${{ secrets.NEXUS_HOST }}/dagestanback:latest
          docker push ${{ secrets.NEXUS_HOST }}/dagestanback:${{ github.run_number }}

  deploy:
    needs: build_and_push
    runs-on: self-hosted
    steps:
      - name: login to nexus and pull images
        run: |
          echo '${{ secrets.NEXUS_PASSWORD }}' | docker login -u ${{ secrets.NEXUS_USERNAME }} --password-stdin  ${{ secrets.NEXUS_HOST }}
          docker-compose pull 
          docker-compose stop
          docker-compose up -d

  cleanup:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Throw away all the garbage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker system prune -f --filter "label!=keep"
