import os

from app.settings import REDIS_URI


CELERY_BROKER_DB = os.getenv('CELERY_BROKER_DB', '1')
CELERY_BROKER_RESULT_DB = os.getenv('CELERY_BROKER_RESULT_DB', '2')
CELERY_BROKER_URI = f'{REDIS_URI}/{CELERY_BROKER_DB}'
CELERY_BROKER_RESULT_URI = f'{REDIS_URI}/{CELERY_BROKER_RESULT_DB}'

CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

CELERY_BROKER_URL = CELERY_BROKER_URI
CELERY_RESULT_BACKEND = CELERY_BROKER_RESULT_URI
